services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: librairie
      MYSQL_USER: user_saejava
      MYSQL_PASSWORD: saejava
    ports:
      - "3306:3306"
    volumes:
      - ./sae-java/src/main/resources/bdd/creation.sql:/docker-entrypoint-initdb.d/creation.sql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://mysql:3306/librairie
      JDBC_DATABASE_USERNAME: sae_user
      JDBC_DATABASE_PASSWORD: sae_password
    volumes:
      - ./facture:/app/facture
    stdin_open: true      
    tty: true